[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/warp1w"
  to = "/.netlify/functions/warp1w"
  status = 200

[[redirects]]
  from = "/warp2w"
  to = "/.netlify/functions/warp2w"
  status = 200

[[redirects]]
  from = "/warp3w"
  to = "/.netlify/functions/warp3w"
  status = 200

[[redirects]]
  from = "/warp4w"
  to = "/.netlify/functions/warp4w"
  status = 200

[[redirects]]
  from = "/warp5"
  to = "/.netlify/functions/warp5"
  status = 200

[[redirects]]
  from = "/warp6"
  to = "/.netlify/functions/warp6"
  status = 200

[[redirects]]
  from = "/warp7"
  to = "/.netlify/functions/warp7"
  status = 200

[[redirects]]
  from = "/warp8"
  to = "/.netlify/functions/warp8"
  status = 200

[[redirects]]
  from = "/warp9"
  to = "/.netlify/functions/warp9"
  status = 200

[[redirects]]
  from = "/warp10w"
  to = "/.netlify/functions/warp10w"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
